sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t lubabalobuwa64/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true lubabalobuwa64/docker-react npm run test